version: '3.7'

services:
   frontend:
      container_name: bnd-frontend
      build:
         context: ./frontend
         dockerfile: Dockerfile.dev
      volumes:
         - ./frontend:/app
      ports:
         - '1100:3000'
      environment:
         - VITE_BACKEND_URL=${VITE_BACKEND_URL}

   backend:
      container_name: bnd-backend
      build:
         context: ./backend
         dockerfile: Dockerfile.dev
      env_file:
         - ./.env
      volumes:
         - ./backend:/app
      ports:
         - '1101:4000'
