services:
   bnd:
      image: ghcr.io/montejojorge/bitcoin-node-dashboard:latest
      container_name: bnd
      ports:
         1100:1101
      volumes:
         - ~/backup-stats:/data
      environment:
         LOGIN_PASSWORD: your-password
         BTC_HOST: 192.168.1.10
         BTC_PORT: 8332
         BTC_USERNAME: your-rpc-usern
         BTC_PASSWORD: your-rpc-password
      restart: unless-stopped