services:
   app:
      container_name: bnd
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 1100:1101
      env_file:
         - ./.env
      depends_on:
         db:
            condition: service_healthy